name: CI/CD Pipeline (Backend & Frontend → ECR → Terraform/EC2)

on:
  push:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd backend
          npm ci
      - name: Run backend tests
        run: |
          cd backend
          npm test
      - name: Run backend coverage
        run: |
          cd backend
          npm run test:coverage
      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/

  push-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Verify AWS credentials and region
        run: |
          aws sts get-caller-identity
          aws ecr describe-repositories --region ${{ secrets.AWS_REGION }} || echo "ECR repo not found, will create."
      - name: Create backend ECR repository if not exists
        env:
          BACKEND_ECR_REPO: ${{ secrets.ECR_REPO_BACKEND }}
          BACKEND_ECR_URL: ${{ secrets.ECR_REPO_BACKEND }}
        run: |
          # Determine backend repo name: prefer explicit secret, else parse from ECR URL
          REPO_NAME="$BACKEND_ECR_REPO"
          if [ -z "$REPO_NAME" ] && [ -n "$BACKEND_ECR_URL" ]; then
            REPO_NAME=$(echo "$BACKEND_ECR_URL" | awk -F/ '{print $2}')
          fi
          if [ -z "$REPO_NAME" ]; then
            echo "No backend ECR repository name provided; skipping creation. Set secret ECR_REPOSITORY_BACKEND or ECR_REPO_URL.";
          else
            aws ecr describe-repositories --repository-names "$REPO_NAME" --region ${{ secrets.AWS_REGION }} || aws ecr create-repository --repository-name "$REPO_NAME" --region ${{ secrets.AWS_REGION }}
          fi
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_BACKEND }}:latest ./backend
          docker push ${{ secrets.ECR_REPO_BACKEND }}:latest

  push-frontend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Verify AWS credentials and region
        run: |
          aws sts get-caller-identity
          aws ecr describe-repositories --region ${{ secrets.AWS_REGION }} || echo "ECR repo not found, will create."
      - name: Create frontend ECR repository if not exists
        env:
          FRONTEND_ECR_REPO: ${{ secrets.ECR_REPO_FRONTEND }}
          FRONTEND_ECR_URL: ${{ secrets.ECR_REPO_FRONTEND }}
        run: |
          # Determine frontend repo name: prefer explicit secret, else parse from ECR URL
          REPO_NAME="$FRONTEND_ECR_REPO"
          if [ -z "$REPO_NAME" ] && [ -n "$FRONTEND_ECR_URL" ]; then
            REPO_NAME=$(echo "$FRONTEND_ECR_URL" | awk -F/ '{print $2}')
          fi
          if [ -z "$REPO_NAME" ]; then
            echo "No frontend ECR repository name provided; skipping creation. Set secret ECR_REPOSITORY_FRONTEND or ECR_REPO_URL_FRONTEND.";
          else
            aws ecr describe-repositories --repository-names "$REPO_NAME" --region ${{ secrets.AWS_REGION }} || aws ecr create-repository --repository-name "$REPO_NAME" --region ${{ secrets.AWS_REGION }}
          fi
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_FRONTEND }}:latest ./frontend
          docker push ${{ secrets.ECR_REPO_FRONTEND }}:latest

  terraform-validate:
    runs-on: ubuntu-latest
    needs: [push-backend, push-frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Export AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV
      - name: Terraform Format
        run: terraform fmt -check -recursive
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: |
          cd infra/terraform
          terraform init
          terraform plan

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: AWS Cleanup (remove duplicates)
        run: |
          pip install awscli
          # Remove duplicate IAM roles
          ROLES=$(aws iam list-roles --query "Roles[?RoleName=='ec2-app-role'].RoleName" --output text)
          for role in $ROLES; do
            aws iam delete-role --role-name $role || true
          done
          aws iam delete-instance-profile --instance-profile-name ec2-app-profile || true
          aws ec2 delete-key-pair --key-name FINALCICD || true
          # Remove excess VPCs if limit is reached (delete all non-default VPCs)
          VPCS=$(aws ec2 describe-vpcs --query 'Vpcs[?IsDefault==`false`].VpcId' --output text)
          for vpc in $VPCS; do
            aws ec2 delete-vpc --vpc-id $vpc || true
          done
          # Remove duplicate ELBv2 Load Balancer and Target Group
          LB_ARN=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?LoadBalancerName=='ec2-app-alb'].LoadBalancerArn" --output text)
          if [ ! -z "$LB_ARN" ]; then
            aws elbv2 delete-load-balancer --load-balancer-arn $LB_ARN || true
          fi
          TG_ARN=$(aws elbv2 describe-target-groups --query "TargetGroups[?TargetGroupName=='ec2-app-tg'].TargetGroupArn" --output text)
          if [ ! -z "$TG_ARN" ]; then
            aws elbv2 delete-target-group --target-group-arn $TG_ARN || true
          fi
          # Remove duplicate Internet Gateways (delete all unattached IGWs)
          IGWS=$(aws ec2 describe-internet-gateways --query 'InternetGateways[?Attachments==`[]`].InternetGatewayId' --output text)
          for igw in $IGWS; do
            aws ec2 delete-internet-gateway --internet-gateway-id $igw || true
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Terraform Apply
        run: |
          cd infra/terraform
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}