name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  backend-test:
    name: Backend tests + coverage
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      NODE_OPTIONS: --experimental-vm-modules
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Run tests
        run: npm test -- --ci --runInBand

      - name: Coverage
        run: npm run test:coverage -- --ci

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage
