name: iac-validate

on:
  push:
    branches: ["**"]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/iac-validate.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/iac-validate.yml"

jobs:
  tf-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
